name: macOS
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS version
        options:
          - macos-latest
          - macos-13
          - macos-12
          - macos-11
jobs:
  action:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: _action_repo
      - run: echo ${{ github.event.inputs.os }} ${{ runner.name }} ${{ runner.os }}
