name: Ubuntu
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS version
        options:
          - ubuntu-latest
          - ubuntu-22.04
          - ubuntu-20.04
jobs:
  action:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: _action_repo
      - run: echo ${{ github.event.inputs.os }} ${{ runner.name }} ${{ runner.os }}
