name: Windows
on:
  workflow_dispatch:
    inputs:
      os:
        type: choice
        description: OS version
        options:
          - windows-latest
          - windows-2022
          - windows-2019
      shell:
        type: choice
        description: Shell
        options:
        - cmd
        - powershell
        - pwsh
        - bash
jobs:
  action:
    runs-on: ${{ github.event.inputs.os }}
    steps:
      - uses: actions/checkout@v3
        with:
          path: _action_repo
      - run: echo ${{ github.event.inputs.shell }} on ${{ github.event.inputs.os }} ${{ runner.name }} ${{ runner.os }}
